// Standalone MSM6258 vector generator matching MAME's okim6258.cpp.
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>

namespace {

constexpr std::array<std::uint8_t, 8> kEncoded = {
    0x70, 0xf1, 0x27, 0x8e, 0x45, 0xab, 0xcd, 0xef,
};
constexpr std::array<int, 8> kIndexShift = {-1, -1, -1, -1, 2, 4, 6, 8};
constexpr std::array<int, 5> kRatePhase = {240, 320, 480, 640, 960};
constexpr std::array<int, 16> kVolumeQ12 = {
    649, 817, 1029, 1295, 1631, 2053, 2584, 3254,
    4096, 5157, 6492, 8173, 10289, 12953, 16306, 20529,
};
constexpr int kPhaseDenominator = 3021;
constexpr std::size_t kMixFrames = 20;

class Decoder {
public:
    std::int16_t clock(std::uint8_t nibble) {
        const int stepval = static_cast<int>(
            std::floor(16.0 * std::pow(11.0 / 10.0, step_)));
        int difference = stepval / 8;
        if (nibble & 1) difference += stepval / 4;
        if (nibble & 2) difference += stepval / 2;
        if (nibble & 4) difference += stepval;
        signal_ += (nibble & 8) ? -difference : difference;
        signal_ = std::clamp(signal_, -512, 511);
        step_ = std::clamp(step_ + kIndexShift[nibble & 7], 0, 48);
        return static_cast<std::int16_t>(signal_ << 4);
    }

private:
    int signal_ = -2;
    int step_ = 0;
};

class Stream {
public:
    std::int16_t next() {
        const std::uint8_t byte = kEncoded[nibble_ / 2];
        const unsigned shift = (nibble_++ & 1) ? 4 : 0;
        return decoder_.clock((byte >> shift) & 0x0f);
    }

private:
    Decoder decoder_;
    std::size_t nibble_ = 0;
};

class Voice {
public:
    Voice(unsigned rate, unsigned volume)
        : phase_increment_(kRatePhase[rate]), gain_(kVolumeQ12[volume]), current_(stream_.next()) {}

    std::int32_t mix_frame() {
        const std::int32_t result = (static_cast<std::int32_t>(current_) * gain_) >> 12;
        phase_ += phase_increment_;
        if (phase_ >= kPhaseDenominator) {
            phase_ -= kPhaseDenominator;
            current_ = stream_.next();
        }
        return result;
    }

private:
    Stream stream_;
    int phase_ = 0;
    int phase_increment_;
    int gain_;
    std::int16_t current_;
};

} // namespace

int main(int argc, char **argv) {
    if (argc != 2 || std::strcmp(argv[1], "--emit-m68k") != 0) {
        std::fprintf(stderr, "usage: %s --emit-m68k\n", argv[0]);
        return 2;
    }

    std::puts("; Generated by tools/pdx_adpcm_oracle.cpp from MAME OKIM6258 semantics.");
    std::printf("PDX_REF_ADPCM_COUNT equ    %zu\n", kEncoded.size() * 2);
    Decoder decoder;
    std::size_t index = 0;
    for (std::uint8_t byte : kEncoded) {
        for (unsigned shift : {0U, 4U}) {
            const std::uint32_t sample = static_cast<std::uint32_t>(
                static_cast<std::int32_t>(decoder.clock((byte >> shift) & 0x0f)));
            std::printf("PDX_REF_ADPCM_%02zu equ      $%08x\n", index++, sample);
        }
    }

    std::printf("PDX_REF_MIX_COUNT equ      %zu\n", kMixFrames);
    Voice fast(4, 8);  // 15.625 kHz, unity
    Voice slow(0, 0);  // 3.90625 kHz, -16 dB
    for (std::size_t frame = 0; frame <= kMixFrames; ++frame) {
        const std::int32_t mixed = std::clamp(
            fast.mix_frame() + slow.mix_frame(), -32768, 32767);
        const std::uint32_t value = static_cast<std::uint32_t>(mixed);
        if (frame < kMixFrames)
            std::printf("PDX_REF_MIX_%02zu equ       $%08x\n", frame, value);
        else
            std::printf("PDX_REF_MIX_PAN_LEFT equ   $%08x\n", value);
    }
    return 0;
}
