// Native YM2151 reference-vector generator using the vendored MAME/ymfm core.

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "ymfm_opm.h"

namespace
{

constexpr uint32_t kX68000Clock = 4'000'000;
constexpr std::array<uint32_t, 4> kLogicalToRawOperator = { 0, 16, 8, 24 };

class oracle_interface : public ymfm::ymfm_interface
{
};

class inspectable_ym2151 : public ymfm::ym2151
{
public:
    explicit inspectable_ym2151(ymfm::ymfm_interface &intf) : ymfm::ym2151(intf) { }

    fm_engine &engine() { return m_fm; }
};

struct trace_event
{
    uint32_t sample;
    uint8_t reg;
    uint8_t data;
};

std::vector<trace_event> load_trace(const std::string &path);

void write_register(inspectable_ym2151 &chip, uint8_t reg, uint8_t data)
{
    chip.write_address(reg);
    chip.write_data(data);
}

uint32_t reference_phase_step()
{
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    // This is the exact register tuple exercised by the Falcon smoke test.
    write_register(chip, 0x28, 0x4c);
    write_register(chip, 0x30, 0x00);
    write_register(chip, 0x40, 0x01);
    write_register(chip, 0xc0, 0x00);

    inspectable_ym2151::output_data output;
    chip.generate(&output);
    return chip.engine().debug_operator(0)->debug_cache().phase_step;
}

void emit_m68k_reference(const std::string &trace_path)
{
    const auto events = load_trace(trace_path);
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    std::cout << "; Generated by tools/ym2151_oracle.cpp from MAME/ymfm.\n";
    std::cout << "YM_REF_PHASE_CH0_OP0 equ     $" << std::hex << std::setw(6)
              << std::setfill('0') << reference_phase_step() << "\n";

    constexpr std::array<uint32_t, 4> checkpoints = { 2, 14, 40, 63 };
    size_t event_index = 0;
    size_t checkpoint_index = 0;
    for (uint32_t sample = 0; sample <= checkpoints.back(); ++sample)
    {
        while (event_index < events.size() && events[event_index].sample == sample)
        {
            write_register(chip, events[event_index].reg, events[event_index].data);
            ++event_index;
        }

        inspectable_ym2151::output_data output;
        chip.generate(&output);
        if (sample == checkpoints[checkpoint_index])
        {
            const uint32_t left = uint32_t(output.data[0]) & 0x00ffffff;
            const uint32_t right = uint32_t(output.data[1]) & 0x00ffffff;
            std::cout << "YM_REF_ATTACK_" << std::dec << sample << "_LEFT equ     $"
                      << std::hex << std::setw(6) << std::setfill('0') << left << "\n";
            std::cout << "YM_REF_ATTACK_" << std::dec << sample << "_RIGHT equ    $"
                      << std::hex << std::setw(6) << std::setfill('0') << right << "\n";
            if (++checkpoint_index == checkpoints.size())
                break;
        }
    }

    // Exercise every OPM connection algorithm with feedback level 4. The
    // trace selects channel 0, so overriding register $20 is sufficient while
    // retaining the same phase/envelope setup and key edge.
    for (uint32_t algorithm = 0; algorithm < 8; ++algorithm)
    {
        oracle_interface algorithm_intf;
        inspectable_ym2151 algorithm_chip(algorithm_intf);
        algorithm_chip.reset();
        size_t algorithm_event = 0;
        inspectable_ym2151::output_data output;
        for (uint32_t sample = 0; sample <= 63; ++sample)
        {
            while (algorithm_event < events.size() && events[algorithm_event].sample == sample)
            {
                const auto &event = events[algorithm_event++];
                const uint8_t data = event.reg == 0x20
                    ? uint8_t(0xc0 | (4 << 3) | algorithm)
                    : event.data;
                write_register(algorithm_chip, event.reg, data);
            }
            algorithm_chip.generate(&output);
        }

        const uint32_t left = uint32_t(output.data[0]) & 0x00ffffff;
        const uint32_t right = uint32_t(output.data[1]) & 0x00ffffff;
        std::cout << "YM_REF_ALGORITHM_" << std::dec << algorithm << "_LEFT equ  $"
                  << std::hex << std::setw(6) << std::setfill('0') << left << "\n";
        std::cout << "YM_REF_ALGORITHM_" << std::dec << algorithm << "_RIGHT equ $"
                  << std::hex << std::setw(6) << std::setfill('0') << right << "\n";
    }
}

std::vector<trace_event> load_trace(const std::string &path)
{
    std::ifstream input(path);
    if (!input)
        throw std::runtime_error("unable to open trace: " + path);

    std::vector<trace_event> events;
    std::string line;
    uint32_t line_number = 0;
    while (std::getline(input, line))
    {
        ++line_number;
        const auto comment = line.find('#');
        if (comment != std::string::npos)
            line.erase(comment);
        std::istringstream parser(line);
        std::string reg_text;
        std::string data_text;
        trace_event event{};
        if (!(parser >> event.sample))
            continue;
        if (!(parser >> reg_text >> data_text))
            throw std::runtime_error("invalid trace line " + std::to_string(line_number));
        event.reg = static_cast<uint8_t>(std::stoul(reg_text, nullptr, 16));
        event.data = static_cast<uint8_t>(std::stoul(data_text, nullptr, 16));
        events.push_back(event);
    }
    return events;
}

void emit_vectors(const std::string &trace_path, uint32_t samples)
{
    const auto events = load_trace(trace_path);
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    std::cout << "# ymfm YM2151; clock=" << kX68000Clock
              << "; rate=" << chip.sample_rate(kX68000Clock)
              << "; trace=" << trace_path << '\n';
    std::cout << "sample\tleft\tright";
    for (uint32_t op = 0; op < 4; ++op)
        std::cout << "\top" << op << "_phase\top" << op << "_step\top" << op
                  << "_env\top" << op << "_state";
    std::cout << '\n';

    size_t event_index = 0;
    for (uint32_t sample = 0; sample < samples; ++sample)
    {
        while (event_index < events.size() && events[event_index].sample == sample)
        {
            write_register(chip, events[event_index].reg, events[event_index].data);
            ++event_index;
        }

        inspectable_ym2151::output_data output;
        chip.generate(&output);
        std::cout << sample << '\t' << output.data[0] << '\t' << output.data[1];
        for (uint32_t raw : kLogicalToRawOperator)
        {
            auto *op = chip.engine().debug_operator(raw);
            std::cout << '\t' << op->phase()
                      << '\t' << op->debug_cache().phase_step
                      << '\t' << op->debug_eg_attenuation()
                      << '\t' << static_cast<uint32_t>(op->debug_eg_state());
        }
        std::cout << '\n';
    }

    if (event_index != events.size())
        throw std::runtime_error("trace contains events beyond requested sample count");
}

} // anonymous namespace

int main(int argc, char **argv)
{
    try
    {
        if (argc == 3 && std::string(argv[1]) == "--emit-m68k")
        {
            emit_m68k_reference(argv[2]);
            return 0;
        }
        if (argc == 2 && std::string(argv[1]) == "--phase-hex")
        {
            std::cout << "0x" << std::hex << std::setw(6) << std::setfill('0')
                      << reference_phase_step() << '\n';
            return 0;
        }
        if (argc == 4 && std::string(argv[1]) == "--vectors")
        {
            emit_vectors(argv[2], static_cast<uint32_t>(std::stoul(argv[3])));
            return 0;
        }

        std::cerr << "usage:\n"
                  << "  ym2151_oracle --emit-m68k TRACE\n"
                  << "  ym2151_oracle --phase-hex\n"
                  << "  ym2151_oracle --vectors TRACE SAMPLES\n";
        return 2;
    }
    catch (const std::exception &error)
    {
        std::cerr << "ym2151_oracle: " << error.what() << '\n';
        return 1;
    }
}
