// Native YM2151 reference-vector generator using the vendored MAME/ymfm core.

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "ymfm_opm.h"
#include "ymfm_fm.ipp"

namespace
{

constexpr uint32_t kX68000Clock = 4'000'000;
constexpr std::array<uint32_t, 4> kLogicalToRawOperator = { 0, 16, 8, 24 };

class oracle_interface : public ymfm::ymfm_interface
{
public:
    void ymfm_set_timer(uint32_t tnum, int32_t duration_in_clocks) override
    {
        m_timer_clocks.at(tnum) = duration_in_clocks;
    }

    void advance(uint32_t clocks)
    {
        for (uint32_t tnum = 0; tnum < m_timer_clocks.size(); ++tnum)
        {
            if (m_timer_clocks[tnum] < 0)
                continue;
            m_timer_clocks[tnum] -= clocks;
            if (m_timer_clocks[tnum] <= 0)
            {
                m_timer_clocks[tnum] = -1;
                m_engine->engine_timer_expired(tnum);
            }
        }
    }

private:
    std::array<int32_t, 2> m_timer_clocks = { -1, -1 };
};

class inspectable_ym2151 : public ymfm::ym2151
{
public:
    explicit inspectable_ym2151(ymfm::ymfm_interface &intf) : ymfm::ym2151(intf) { }

    fm_engine &engine() { return m_fm; }
};

struct trace_event
{
    uint32_t sample;
    uint8_t reg;
    uint8_t data;
};

std::vector<trace_event> load_trace(const std::string &path);

void write_register(inspectable_ym2151 &chip, uint8_t reg, uint8_t data)
{
    chip.write_address(reg);
    chip.write_data(data);
}

uint32_t reference_phase_step()
{
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    // This is the exact register tuple exercised by the Falcon smoke test.
    write_register(chip, 0x28, 0x4c);
    write_register(chip, 0x30, 0x00);
    write_register(chip, 0x40, 0x01);
    write_register(chip, 0xc0, 0x00);

    inspectable_ym2151::output_data output;
    chip.generate(&output);
    return chip.engine().debug_operator(0)->debug_cache().phase_step;
}

void emit_m68k_reference(const std::string &trace_path, const std::string &noise_trace_path,
    const std::string &csm_trace_path, const std::string &vibrato_trace_path)
{
    const auto events = load_trace(trace_path);
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    std::cout << "; Generated by tools/ym2151_oracle.cpp from MAME/ymfm.\n";
    std::cout << "YM_REF_PHASE_CH0_OP0 equ     $" << std::hex << std::setw(6)
              << std::setfill('0') << reference_phase_step() << "\n";

    constexpr std::array<uint32_t, 4> checkpoints = { 2, 14, 40, 63 };
    size_t event_index = 0;
    size_t checkpoint_index = 0;
    for (uint32_t sample = 0; sample <= checkpoints.back(); ++sample)
    {
        while (event_index < events.size() && events[event_index].sample == sample)
        {
            write_register(chip, events[event_index].reg, events[event_index].data);
            ++event_index;
        }

        inspectable_ym2151::output_data output;
        chip.generate(&output);
        if (sample == checkpoints[checkpoint_index])
        {
            const uint32_t left = uint32_t(output.data[0]) & 0x00ffffff;
            const uint32_t right = uint32_t(output.data[1]) & 0x00ffffff;
            std::cout << "YM_REF_ATTACK_" << std::dec << sample << "_LEFT equ     $"
                      << std::hex << std::setw(6) << std::setfill('0') << left << "\n";
            std::cout << "YM_REF_ATTACK_" << std::dec << sample << "_RIGHT equ    $"
                      << std::hex << std::setw(6) << std::setfill('0') << right << "\n";
            if (++checkpoint_index == checkpoints.size())
                break;
        }
    }

    // Exercise every OPM connection algorithm with feedback level 4. The
    // trace selects channel 0, so overriding register $20 is sufficient while
    // retaining the same phase/envelope setup and key edge.
    for (uint32_t algorithm = 0; algorithm < 8; ++algorithm)
    {
        oracle_interface algorithm_intf;
        inspectable_ym2151 algorithm_chip(algorithm_intf);
        algorithm_chip.reset();
        size_t algorithm_event = 0;
        inspectable_ym2151::output_data output;
        for (uint32_t sample = 0; sample <= 63; ++sample)
        {
            while (algorithm_event < events.size() && events[algorithm_event].sample == sample)
            {
                const auto &event = events[algorithm_event++];
                const uint8_t data = event.reg == 0x20
                    ? uint8_t(0xc0 | (4 << 3) | algorithm)
                    : event.data;
                write_register(algorithm_chip, event.reg, data);
            }
            algorithm_chip.generate(&output);
        }

        const uint32_t left = uint32_t(output.data[0]) & 0x00ffffff;
        const uint32_t right = uint32_t(output.data[1]) & 0x00ffffff;
        std::cout << "YM_REF_ALGORITHM_" << std::dec << algorithm << "_LEFT equ  $"
                  << std::hex << std::setw(6) << std::setfill('0') << left << "\n";
        std::cout << "YM_REF_ALGORITHM_" << std::dec << algorithm << "_RIGHT equ $"
                  << std::hex << std::setw(6) << std::setfill('0') << right << "\n";
    }

    const auto noise_events = load_trace(noise_trace_path);
    oracle_interface noise_intf;
    inspectable_ym2151 noise_chip(noise_intf);
    noise_chip.reset();
    size_t noise_event = 0;
    inspectable_ym2151::output_data noise_output;
    for (uint32_t sample = 0; sample <= 63; ++sample)
    {
        while (noise_event < noise_events.size() && noise_events[noise_event].sample == sample)
        {
            const auto &event = noise_events[noise_event++];
            write_register(noise_chip, event.reg, event.data);
        }
        noise_chip.generate(&noise_output);
    }
    const uint32_t noise_left = uint32_t(noise_output.data[0]) & 0x00ffffff;
    const uint32_t noise_right = uint32_t(noise_output.data[1]) & 0x00ffffff;
    std::cout << "YM_REF_NOISE_63_LEFT equ     $" << std::hex << std::setw(6)
              << std::setfill('0') << noise_left << "\n";
    std::cout << "YM_REF_NOISE_63_RIGHT equ    $" << std::hex << std::setw(6)
              << std::setfill('0') << noise_right << "\n";

    // Timer A is programmed for a two-sample period. It expires after sample
    // 1, so the CSM key pulse is consumed by prepare() at the start of sample
    // 2. Timer status remains clear because the trace leaves enable-A off.
    const auto csm_events = load_trace(csm_trace_path);
    oracle_interface csm_intf;
    inspectable_ym2151 csm_chip(csm_intf);
    csm_chip.reset();
    size_t csm_event = 0;
    inspectable_ym2151::output_data csm_output;
    for (uint32_t sample = 0; sample <= 2; ++sample)
    {
        while (csm_event < csm_events.size() && csm_events[csm_event].sample == sample)
        {
            const auto &event = csm_events[csm_event++];
            write_register(csm_chip, event.reg, event.data);
        }
        csm_chip.generate(&csm_output);
        csm_intf.advance(64);
    }
    const uint32_t csm_left = uint32_t(csm_output.data[0]) & 0x00ffffff;
    const uint32_t csm_right = uint32_t(csm_output.data[1]) & 0x00ffffff;
    std::cout << "YM_REF_CSM_2_LEFT equ        $" << std::hex << std::setw(6)
              << std::setfill('0') << csm_left << "\n";
    std::cout << "YM_REF_CSM_2_RIGHT equ       $" << std::hex << std::setw(6)
              << std::setfill('0') << csm_right << "\n";

    // Maximum-rate saw vibrato with PMS 7 keeps the per-sample LFO PM value
    // non-zero for most of the window, exercising the dynamic phase-step
    // derivation rather than the cached no-PM path.
    const auto vibrato_events = load_trace(vibrato_trace_path);
    oracle_interface vibrato_intf;
    inspectable_ym2151 vibrato_chip(vibrato_intf);
    vibrato_chip.reset();
    size_t vibrato_event = 0;
    inspectable_ym2151::output_data vibrato_output;
    for (uint32_t sample = 0; sample <= 63; ++sample)
    {
        while (vibrato_event < vibrato_events.size()
            && vibrato_events[vibrato_event].sample == sample)
        {
            const auto &event = vibrato_events[vibrato_event++];
            write_register(vibrato_chip, event.reg, event.data);
        }
        vibrato_chip.generate(&vibrato_output);
    }
    const uint32_t vibrato_left = uint32_t(vibrato_output.data[0]) & 0x00ffffff;
    const uint32_t vibrato_right = uint32_t(vibrato_output.data[1]) & 0x00ffffff;
    std::cout << "YM_REF_VIBRATO_63_LEFT equ   $" << std::hex << std::setw(6)
              << std::setfill('0') << vibrato_left << "\n";
    std::cout << "YM_REF_VIBRATO_63_RIGHT equ  $" << std::hex << std::setw(6)
              << std::setfill('0') << vibrato_right << "\n";
}

std::vector<trace_event> load_trace(const std::string &path)
{
    std::ifstream input(path);
    if (!input)
        throw std::runtime_error("unable to open trace: " + path);

    std::vector<trace_event> events;
    std::string line;
    uint32_t line_number = 0;
    while (std::getline(input, line))
    {
        ++line_number;
        const auto comment = line.find('#');
        if (comment != std::string::npos)
            line.erase(comment);
        std::istringstream parser(line);
        std::string reg_text;
        std::string data_text;
        trace_event event{};
        if (!(parser >> event.sample))
            continue;
        if (!(parser >> reg_text >> data_text))
            throw std::runtime_error("invalid trace line " + std::to_string(line_number));
        event.reg = static_cast<uint8_t>(std::stoul(reg_text, nullptr, 16));
        event.data = static_cast<uint8_t>(std::stoul(data_text, nullptr, 16));
        events.push_back(event);
    }
    return events;
}

void emit_vectors(const std::string &trace_path, uint32_t samples)
{
    const auto events = load_trace(trace_path);
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    std::cout << "# ymfm YM2151; clock=" << kX68000Clock
              << "; rate=" << chip.sample_rate(kX68000Clock)
              << "; trace=" << trace_path << '\n';
    std::cout << "sample\tleft\tright";
    for (uint32_t op = 0; op < 4; ++op)
        std::cout << "\top" << op << "_phase\top" << op << "_step\top" << op
                  << "_env\top" << op << "_state";
    std::cout << '\n';

    size_t event_index = 0;
    for (uint32_t sample = 0; sample < samples; ++sample)
    {
        while (event_index < events.size() && events[event_index].sample == sample)
        {
            write_register(chip, events[event_index].reg, events[event_index].data);
            ++event_index;
        }

        inspectable_ym2151::output_data output;
        chip.generate(&output);
        intf.advance(64);
        std::cout << sample << '\t' << output.data[0] << '\t' << output.data[1];
        for (uint32_t raw : kLogicalToRawOperator)
        {
            auto *op = chip.engine().debug_operator(raw);
            std::cout << '\t' << op->phase()
                      << '\t' << op->debug_cache().phase_step
                      << '\t' << op->debug_eg_attenuation()
                      << '\t' << static_cast<uint32_t>(op->debug_eg_state());
        }
        std::cout << '\n';
    }

    if (event_index != events.size())
        throw std::runtime_error("trace contains events beyond requested sample count");
}

uint32_t hash_event(uint32_t hash, const trace_event &event, uint8_t data)
{
    // FNV-1a over the exact native timestamp and adjusted register payload.
    // A zero hash is reserved for codec frames that apply no writes.
    for (uint32_t value : { event.sample, uint32_t(event.reg), uint32_t(data) })
    {
        for (uint32_t shift = 0; shift < 32; shift += 8)
        {
            hash ^= (value >> shift) & 0xff;
            hash *= 16'777'619U;
        }
    }
    return hash;
}

class perceptual_renderer
{
public:
    void render(inspectable_ym2151 &chip, inspectable_ym2151::output_data &output)
    {
        static constexpr std::array<uint16_t, 8> kAlgorithmOps = {
            0x035, 0x03a, 0x064, 0x071, 0x131, 0x313, 0x301, 0x380
        };
        auto &engine = chip.engine();
        auto &regs = engine.regs();
        output.clear();

        // Experimental sweep hook: YM_MODEL_FOLD_MODE simulates the DSP
        // kernel's coupled M1 gain fold k (serial-from-O1 and the raw
        // feedback-pair sum both shift by 1+k; O1 as a carrier is
        // unaffected, and the all-carrier algorithm 7 keeps feedback at the
        // fold depth through its two-product stage). Unset = exact ymfm.
        static const int fold_mode = [] {
            const char *value = std::getenv("YM_MODEL_FOLD_MODE");
            return value ? std::atoi(value) : -1;
        }();
        static const int fold_fixed = [] {
            const char *value = std::getenv("YM_MODEL_FOLD_K");
            return value ? std::atoi(value) : 0;
        }();
        // mode 3: half fold plus a per-algorithm bias, eight comma-free
        // digits (value minus 5) in YM_MODEL_FOLD_BIAS, e.g. "56655525".
        static const std::array<int, 8> fold_bias = [] {
            std::array<int, 8> bias{};
            const char *value = std::getenv("YM_MODEL_FOLD_BIAS");
            if (value && std::strlen(value) == 8)
                for (int i = 0; i < 8; ++i)
                    bias[i] = value[i] - '0' - 5;
            return bias;
        }();

        for (uint32_t channel = 0; channel < 8; ++channel)
        {
            // The perceptual kernel advances feedback once per produced codec
            // frame, not once per exact native sample.
            m_feedback_0[channel] = m_feedback_1[channel];
            m_feedback_1[channel] = m_feedback_in[channel];

            const std::array<uint32_t, 4> raw = {
                channel, channel + 16, channel + 8, channel + 24
            };
            const uint32_t am_offset = regs.lfo_am_offset(channel);
            const uint32_t feedback = regs.ch_feedback(channel);
            const uint32_t algorithm = regs.ch_algorithm(channel);
            int fold = 0;
            if (fold_mode == 0)
                fold = fold_fixed;
            else if (fold_mode == 1)
                fold = feedback ? int(9 - feedback) : 0;
            else if (fold_mode == 2)
                fold = feedback ? int(10 - feedback) / 2 : 0;
            else if (fold_mode == 3)
                fold = feedback
                    ? std::max(0, int(10 - feedback) / 2 + fold_bias[algorithm])
                    : 0;
            int32_t modulation;
            if (feedback == 0)
                modulation = 0;
            else if (fold_mode < 0)
                modulation = (m_feedback_0[channel] + m_feedback_1[channel])
                    >> (10 - feedback);
            else
            {
                // The kernel's level-7 history-precise stage halves only the
                // stored feedback pair, landing the SELF path exactly on
                // ymfm's (out0+out1)>>3 depth while the onward fold depth is
                // untouched; without it the coupled fold's doubled loop gain
                // sustains a frame-rate limit cycle over long renders.
                const int self_extra = feedback == 7 ? 1 : 0;
                modulation = (m_feedback_0[channel] + m_feedback_1[channel])
                    >> (1 + fold + self_extra);
            }

            std::array<int32_t, 8> operator_output{};
            const int32_t out1_carrier = m_feedback_in[channel] = quantized_volume(
                *engine.debug_operator(raw[0]), modulation, am_offset);
            // Every modulation lookup sees O1 at the folded gain; only the
            // all-carrier algorithm 7 consumes the unfolded value below.
            operator_output[1] = fold_mode < 0
                ? out1_carrier
                : (out1_carrier >> fold);

            const uint16_t topology = kAlgorithmOps[algorithm];
            modulation = operator_output[(topology >> 0) & 1] >> 1;
            operator_output[2] = quantized_volume(
                *engine.debug_operator(raw[1]), modulation, am_offset);
            operator_output[5] = operator_output[1] + operator_output[2];

            modulation = operator_output[(topology >> 1) & 7] >> 1;
            operator_output[3] = quantized_volume(
                *engine.debug_operator(raw[2]), modulation, am_offset);
            operator_output[6] = operator_output[1] + operator_output[3];
            operator_output[7] = operator_output[2] + operator_output[3];

            int32_t result;
            if (regs.noise_enable() && channel == 7)
                result = engine.debug_operator(raw[3])->compute_noise_volume(am_offset);
            else
            {
                modulation = operator_output[(topology >> 4) & 7] >> 1;
                result = quantized_volume(
                    *engine.debug_operator(raw[3]), modulation, am_offset);
            }

            if ((topology & 0x080) != 0)
                result = std::clamp(result + out1_carrier, -32768, 32767);
            if ((topology & 0x100) != 0)
                result = std::clamp(result + operator_output[2], -32768, 32767);
            if ((topology & 0x200) != 0)
                result = std::clamp(result + operator_output[3], -32768, 32767);

            if (regs.ch_output_0(channel))
                output.data[0] += result;
            if (regs.ch_output_1(channel))
                output.data[1] += result;
        }
        output.roundtrip_fp();
    }

private:
    static int32_t quantized_volume(ymfm::fm_operator<ymfm::opm_registers> &op,
        int32_t modulation, uint32_t am_offset)
    {
        // ymfm addresses a 1024-step logical waveform. Clearing its low two
        // phase bits projects that address onto the DSP56001's 256-step ROM.
        const uint32_t phase = (op.phase() + modulation) & ~uint32_t(3);
        return op.compute_volume(phase, am_offset);
    }

    std::array<int32_t, 8> m_feedback_0{};
    std::array<int32_t, 8> m_feedback_1{};
    std::array<int32_t, 8> m_feedback_in{};
};

void emit_codec_vectors(const std::string &trace_path, uint32_t frames,
    int32_t algorithm_override, int32_t feedback_override, bool perceptual)
{
    if (algorithm_override < -1 || algorithm_override > 7)
        throw std::runtime_error("algorithm override must be 0-7");
    if (feedback_override < -1 || feedback_override > 7)
        throw std::runtime_error("feedback override must be 0-7");

    const auto events = load_trace(trace_path);
    oracle_interface intf;
    inspectable_ym2151 chip(intf);
    chip.reset();

    // Match the Falcon codec exactly: 25.175 MHz / 4 / 128. The rational
    // native-to-codec schedule is represented by 1280/1007 and is the same
    // zero-order policy used by ssi_render_frame in the exact DSP path.
    constexpr uint32_t kCodecNumerator = 1280;
    constexpr uint32_t kCodecDenominator = 1007;
    constexpr double kCodecRate = 25'175'000.0 / 4.0 / 128.0;
    std::cout << "# ymfm YM2151 "
              << (perceptual ? "codec-rate perceptual projection" : "exact codec reference")
              << "; native_rate="
              << chip.sample_rate(kX68000Clock)
              << "; codec_rate=" << std::fixed << std::setprecision(6) << kCodecRate
              << "; ratio=" << kCodecNumerator << '/' << kCodecDenominator
              << "; event_policy=before_exact_native_sample; trace=" << trace_path;
    if (algorithm_override >= 0)
        std::cout << "; algorithm=" << algorithm_override;
    if (feedback_override >= 0)
        std::cout << "; feedback=" << feedback_override;
    std::cout << '\n';
    std::cout << "frame\tnative_sample\tevent_count\tevent_hash\tleft\tright"
              << "\tlfo_am\tnoise_state";
    for (uint32_t op = 0; op < 4; ++op)
        std::cout << "\top" << op << "_phase\top" << op << "_step\top" << op
                  << "_env\top" << op << "_state";
    std::cout << '\n';

    size_t event_index = 0;
    uint32_t native_sample = 0;
    uint32_t resample_phase = 0;
    inspectable_ym2151::output_data output{};
    perceptual_renderer renderer;
    for (uint32_t frame = 0; frame < frames; ++frame)
    {
        uint32_t event_count = 0;
        uint32_t event_hash = 2'166'136'261U;
        uint32_t last_native_sample = native_sample;
        resample_phase += kCodecNumerator;
        do
        {
            resample_phase -= kCodecDenominator;
            while (event_index < events.size() && events[event_index].sample == native_sample)
            {
                const auto &event = events[event_index++];
                uint8_t data = event.data;
                if (event.reg == 0x20)
                {
                    if (algorithm_override >= 0)
                        data = uint8_t((data & ~0x07) | algorithm_override);
                    if (feedback_override >= 0)
                        data = uint8_t((data & ~0x38) | (feedback_override << 3));
                }
                write_register(chip, event.reg, data);
                event_hash = hash_event(event_hash, event, data);
                ++event_count;
            }

            chip.generate(&output);
            intf.advance(64);
            last_native_sample = native_sample++;
        }
        while (resample_phase >= kCodecDenominator);

        if (perceptual)
            renderer.render(chip, output);

        std::cout << std::dec << frame << '\t' << last_native_sample << '\t'
                  << event_count << '\t' << (event_count == 0 ? 0 : event_hash)
                  << '\t' << output.data[0] << '\t' << output.data[1]
                  << '\t' << chip.engine().regs().lfo_am_offset(0)
                  << '\t' << chip.engine().regs().noise_state();
        for (uint32_t raw : kLogicalToRawOperator)
        {
            auto *op = chip.engine().debug_operator(raw);
            std::cout << '\t' << op->phase()
                      << '\t' << op->debug_cache().phase_step
                      << '\t' << op->debug_eg_attenuation()
                      << '\t' << static_cast<uint32_t>(op->debug_eg_state());
        }
        std::cout << '\n';
    }

    if (event_index != events.size())
        throw std::runtime_error("trace contains events beyond requested codec frame count");
}

} // anonymous namespace

int main(int argc, char **argv)
{
    try
    {
        if (argc == 6 && std::string(argv[1]) == "--emit-m68k")
        {
            emit_m68k_reference(argv[2], argv[3], argv[4], argv[5]);
            return 0;
        }
        if (argc == 2 && std::string(argv[1]) == "--phase-hex")
        {
            std::cout << "0x" << std::hex << std::setw(6) << std::setfill('0')
                      << reference_phase_step() << '\n';
            return 0;
        }
        if (argc == 4 && std::string(argv[1]) == "--vectors")
        {
            emit_vectors(argv[2], static_cast<uint32_t>(std::stoul(argv[3])));
            return 0;
        }
        if (argc >= 4 && (std::string(argv[1]) == "--codec-vectors"
            || std::string(argv[1]) == "--perceptual-vectors"))
        {
            const bool perceptual = std::string(argv[1]) == "--perceptual-vectors";
            int32_t algorithm_override = -1;
            int32_t feedback_override = -1;
            for (int arg = 4; arg < argc; ++arg)
            {
                const std::string option = argv[arg];
                if (option == "--algorithm" && arg + 1 < argc)
                    algorithm_override = static_cast<int32_t>(std::stol(argv[++arg]));
                else if (option == "--feedback" && arg + 1 < argc)
                    feedback_override = static_cast<int32_t>(std::stol(argv[++arg]));
                else
                    throw std::runtime_error("invalid --codec-vectors option: " + option);
            }
            emit_codec_vectors(argv[2], static_cast<uint32_t>(std::stoul(argv[3])),
                algorithm_override, feedback_override, perceptual);
            return 0;
        }

        std::cerr << "usage:\n"
                  << "  ym2151_oracle --emit-m68k ATTACK_TRACE NOISE_TRACE CSM_TRACE VIBRATO_TRACE\n"
                  << "  ym2151_oracle --phase-hex\n"
                  << "  ym2151_oracle --vectors TRACE SAMPLES\n"
                  << "  ym2151_oracle --codec-vectors TRACE FRAMES"
                     " [--algorithm 0-7] [--feedback 0-7]\n"
                  << "  ym2151_oracle --perceptual-vectors TRACE FRAMES"
                     " [--algorithm 0-7] [--feedback 0-7]\n";
        return 2;
    }
    catch (const std::exception &error)
    {
        std::cerr << "ym2151_oracle: " << error.what() << '\n';
        return 1;
    }
}
